@startuml
'https://plantuml.com/state-diagram

!theme blueprint
hide empty description
title Additive Level Load (faster)
scale 612 width


concise "Loading Scene" as loading
concise "Current Level" as current
concise "Next Level" as next
concise "UnloadUnusedAssets()" as unload
robust "Memory Usage" as memory

memory has Higher
memory has Normal
memory has Lower

current is Loaded
memory is Normal

@0
loading is Load

@2
loading is ""
current is UnloadAsync

@4
current is {hidden}
next is LoadAsync
memory is Higher

@6
next is Loaded
unload is Runs
memory is Normal

@7
unload is {hidden}
loading is Unload

@9
loading is {hidden}

@10


highlight 2 to 7 #336699;line:DimGrey : "User sees loading screen ..."

@enduml
