@startuml
'https://plantuml.com/state-diagram

!theme blueprint
hide empty description
title Server Scene Flow
scale 612 width

state "Launch Scene" as launch {
    state "DontDestroyOnLoad" as persistent
    note right of persistent : NetworkManager ..
}

state "Online Scene" as online {
    state "Additive Scenes" as ingame
    note right of ingame : World, Server Logic ..
}

[*] -> launch
launch --> online : StartServer()
online --> online : Restart Session

@enduml
