FSM.State Class Reference
Represents a state in a statemachine.
Public Member Functions
State (String stateName)
Create a new named state.
Transition AddTransition ()
Add an empty transition to this state.
Transition AddTransition (String transitionName)
Add a named transition to this state.
Transition AddTransition (Transition transition)
Add the given transition.
State AddTransitions (params Transition[] transitions)
Add multiple transitions.
Boolean IsFinalState ()
Is true if the State has no conditions. It is a so-called final state from which there is no return. Such a state ends the statemachine.
void Update (FSM sm)
Updating the state will update all its transitions.
Properties
Boolean Logging [get, set]
Whether this state has logging enabled.
String Name [get]
The State's name.
Detailed Description
Represents a state in a statemachine.
Definition at line 16 of file FSM.State.cs.
Constructor & Destructor Documentation
State()
State (String stateName)
Create a new named state.
Parameters
stateName
References FSM.State.Name.
Member Function Documentation
AddTransition() [1/3]
Transition AddTransition ()
Add an empty transition to this state.
Returns
AddTransition() [2/3]
Transition AddTransition (String transitionName)
Add a named transition to this state.
Parameters
transitionName
Returns
AddTransition() [3/3]
Transition AddTransition (Transition transition)
Add the given transition.
Parameters
transition
Returns
Definition at line 84 of file FSM.State.cs.
            {
                AddTransitions(transition);
                return transition;
            }
References FSM.State.AddTransitions().
AddTransitions()
State AddTransitions (params Transition[] transitions)
Add multiple transitions.
Parameters
transitions
Returns
Exceptions
ArgumentException
Definition at line 96 of file FSM.State.cs.
            {
                if (transitions == null || transitions.Length == 0)
                    throw new ArgumentException("transitions null or empty");
                if (m_Transitions == null)
                    m_Transitions = transitions;
                else
                {
                    var startIndex = m_Transitions.Length;
                    var addCount = transitions.Length;
                    Array.Resize(ref m_Transitions, startIndex + addCount);
                    for (var i = 0; i < addCount; i++)
                        m_Transitions[startIndex + i] = transitions[i];
                }
                return this;
            }
Referenced by FSM.State.AddTransition().
IsFinalState()
Boolean IsFinalState ()
Is true if the State has no conditions. It is a so-called final state from which there is no return. Such a state ends the statemachine.
Returns
Referenced by FSM.Update().
Update()
void Update (FSM sm)
Updating the state will update all its transitions.
Parameters
sm
Definition at line 127 of file FSM.State.cs.
            {
                foreach (var transition in Transitions)
                {
                    transition.Update(sm);
                    // stop evaluating further transitions if the current transition caused a state change
                    if (sm.DidChangeState)
                        break;
                }
            }
Referenced by FSM.Update().
Property Documentation
Logging
Boolean Logging [get], [set]
Whether this state has logging enabled.
Definition at line 29 of file FSM.State.cs.
{ get; set; }
Name
String Name [get]
The State's name.
Definition at line 25 of file FSM.State.cs.
{ get; }
Referenced by FSM.State.State().