FSM Class Reference
Represents a finite-statemachine with a set of local and global variables indexed by name.
Classes
class State
Represents a state in a statemachine.
struct StateChangeEventArgs
Sent with state change event.
struct StatemachineStoppedEventArgs
Sent with Statemachine stopped event.
class Transition
Represents a transition in a statemachine. A transition can also be a self-transition that does not change state.
Public Member Functions
FSM (String statemachineName)
Creates a named Statemachine instance.
FSM Start ()
Initializes (starts) the statemachine.
override String ToString ()
void Update ()
Evaluates the statemachine's states and their transitions.
FSM WithStates (params State[] states)
Provides the states for the statemachine. Must only be called once per statemachine.
FSM WithStates (params String[] stateNames)
Creates several named States. For use with Enum.GetNames().
Static Public Member Functions
static LambdaAction Action (Action callback)
Creates a new generic lambda Action. Mainly intended for prototyping.
static LogicalAnd AND (params ICondition[] conditions)
Logical AND condition will be true if all of the containing conditions are true.
static LambdaCondition Condition (Func< Boolean > callback)
Creates a new generic lambda Condition. Mainly intended for prototyping.
static State CreateState (String stateName)
Creates a new State.
static State[] CreateStates (params String[] stateNames)
Creates multiple States from strings.
static Transition CreateTransition ()
Creates a new unnamed transition.
static Transition CreateTransition (String transitionName)
Creates a named transition to the target state.
static LogicalNand NAND (params ICondition[] conditions)
Logical NAND condition will be true if one or all of the containing conditions are false.
static LogicalNor NOR (params ICondition[] conditions)
Logical NOR condition will be true only if both conditions are false.
static LogicalNot NOT (ICondition condition)
static LogicalOr OR (params ICondition[] conditions)
Logical OR condition will be true if one or more of the containing conditions are true.
Properties
State ActiveState [get]
The currently active State.
Int32 ActiveStateIndex = -1 [get]
Boolean AllowMultipleStateChanges [get, set]
If true, evaluation continues after a state change occured. If false, a state change will exit Evaluate().
Boolean DidChangeState [get]
In addition to the OnStateChange event this can be used to check if a state change occured. The value persists until the next call to Evaluate().
Boolean IsStopped [get]
Is true if the Statemachine reached a "final state", a state without any transitions.
Boolean Logging [get, set]
Int32 MaxStateChangesPerEvaluate = 100 [get, set]
How many state changes may occur in a single Evaluate() before execution is interrupted.
String Name [get]
Name of the Statemachine.
State[] States [get]
Variables StaticVars [get]
Global variables are available for all statemachines (be mindful!).
Variables Vars = new() [get]
These variables are unique to the Statemachine instance.
Events
Action< StateChangeEventArgs > OnStateChange
Invoked after each state change.
Action< StatemachineStoppedEventArgs > OnStopped
Invoked when the statemachine entered a final state (state without any transitions).
Detailed Description
Represents a finite-statemachine with a set of local and global variables indexed by name.
Definition at line 10 of file FSM.Transition.cs.
Constructor & Destructor Documentation
FSM()
FSM (String statemachineName)
Creates a named Statemachine instance.
Parameters
statemachineName Name or description (required)
Member Function Documentation
Action()
static LambdaAction Action (Action callback) [static]
Creates a new generic lambda Action. Mainly intended for prototyping.
Parameters
callback
Returns
AND()
static LogicalAnd AND (params ICondition[] conditions) [static]
Logical AND condition will be true if all of the containing conditions are true.
Logical AND is the default operation for Conditions. This AND operator is intended to be used within an OR condition to express more complex conditions like so: OR(AND(a,b), AND(c,d), AND(e,f,g,h))
Parameters
conditions Two or more ICondition instances.
Returns
Condition()
static LambdaCondition Condition (Func< Boolean > callback) [static]
Creates a new generic lambda Condition. Mainly intended for prototyping.
Parameters
callback
Returns
CreateState()
static State CreateState (String stateName) [static]
Creates a new State.
Parameters
stateName
Returns
CreateStates()
static State[] CreateStates (params String[] stateNames) [static]
Creates multiple States from strings.
Parameters
stateName
Returns
Definition at line 26 of file FSM.Static.cs.
        {
            if (stateNames == null)
                throw new ArgumentNullException(nameof(stateNames));
            var stateCount = stateNames.Length;
            var states = new State[stateCount];
            for (var i = 0; i < stateCount; i++)
                states[i] = new State(stateNames[i]);
            return states;
        }
Referenced by FSM.WithStates().
CreateTransition() [1/2]
static Transition CreateTransition () [static]
Creates a new unnamed transition.
Returns
CreateTransition() [2/2]
static Transition CreateTransition (String transitionName) [static]
Creates a named transition to the target state.
Parameters
transitionName
gotoState
Returns
NAND()
static LogicalNand NAND (params ICondition[] conditions) [static]
Logical NAND condition will be true if one or all of the containing conditions are false.
Parameters
conditions Two or more ICondition instances.
Returns
NOR()
static LogicalNor NOR (params ICondition[] conditions) [static]
Logical NOR condition will be true only if both conditions are false.
Parameters
conditions
Returns
NOT()
static LogicalNot NOT (ICondition condition) [static]
Logical NOT condition will be true if the containing condition evaluates to false, and vice versa.
Parameters
condition
Returns
OR()
static LogicalOr OR (params ICondition[] conditions) [static]
Logical OR condition will be true if one or more of the containing conditions are true.
Parameters
conditions Two or more ICondition instances.
Returns
Start()
FSM Start ()
Initializes (starts) the statemachine.
Returns
Definition at line 148 of file FSM.cs.
        {
            if (IsStarted)
                throw new InvalidOperationException($"FSM '{Name}': Start() must only be called once");
            ActiveStateIndex = 0;
            ApplyLoggingToAllStates(Logging);
            foreach (var state in States)
                state.OnStart(this);
            ValidateStatemachine();
            ActiveState.OnEnterState(this);
            return this;
        }
References FSM.ActiveState.
Update()
void Update ()
Evaluates the statemachine's states and their transitions.
Definition at line 178 of file FSM.cs.
        {
            ThrowIfStatemachineNotStarted();
            if (IsStopped)
                return;
            var iterations = AllowMultipleStateChanges ? MaxStateChangesPerEvaluate : 0;
            do
            {
                //Debug.Log($"[{Time.frameCount}] FSM Update: iteration #{MaxStateChangesPerEvaluate-iterations}");
                DidChangeState = false;
                var updatingState = ActiveState;
                updatingState.Update(this);
                if (DidChangeState)
                {
                    updatingState.OnExitState(this);
                    ActiveState.OnEnterState(this);
                    InvokeOnStateChangeEvent(updatingState);
                    if (ActiveState.IsFinalState())
                    {
                        Stop();
                        InvokeOnStoppedEvent();
                    }
                    iterations--;
                }
                if (IsStopped || DidChangeState == false)
                    break;
                if (AllowMultipleStateChanges)
                    WarnIfIterationsExceeded(iterations);
            } while (iterations > 0);
        }
References FSM.ActiveState, FSM.AllowMultipleStateChanges, FSM.DidChangeState, FSM.IsStopped, and FSM.MaxStateChangesPerEvaluate.
WithStates() [1/2]
FSM WithStates (params State[] states)
Provides the states for the statemachine. Must only be called once per statemachine.
Parameters
states
Returns
Exceptions
InvalidOperationException
Definition at line 132 of file FSM.cs.
        {
            if (States != null)
                throw new InvalidOperationException("States already set!");
            if (states == null)
                throw new ArgumentNullException(nameof(states));
            m_States = states;
            return this;
        }
WithStates() [2/2]
FSM WithStates (params String[] stateNames)
Creates several named States. For use with Enum.GetNames().
Ideal for use with Enum.GetNames().
Parameters
stateNames
Returns
Definition at line 118 of file FSM.cs.
        {
            var states = CreateStates(stateNames);
            WithStates(states);
            return this;
        }
References FSM.CreateStates(), and FSM.WithStates().
Referenced by FSM.WithStates().
Property Documentation
ActiveState
State ActiveState [get]
The currently active State.
Only use this after calling Start().
Definition at line 54 of file FSM.cs.
        {
            get
            {
                ThrowIfStatemachineNotStarted();
                return States[ActiveStateIndex];
            }
        }
Referenced by FSM.Start(), and FSM.Update().
ActiveStateIndex
Int32 ActiveStateIndex = -1 [get]
Definition at line 31 of file FSM.cs.
{ get; private set; } = -1;
AllowMultipleStateChanges
Boolean AllowMultipleStateChanges [get], [set]
If true, evaluation continues after a state change occured. If false, a state change will exit Evaluate().
Definition at line 81 of file FSM.cs.
{ get; set; }
Referenced by FSM.Update().
DidChangeState
Boolean DidChangeState [get]
In addition to the OnStateChange event this can be used to check if a state change occured. The value persists until the next call to Evaluate().
Definition at line 90 of file FSM.cs.
{ get; private set; }
Referenced by FSM.Update().
IsStopped
Boolean IsStopped [get]
Is true if the Statemachine reached a "final state", a state without any transitions.
Definition at line 85 of file FSM.cs.
Referenced by FSM.Update().
Logging
Boolean Logging [get], [set]
Definition at line 32 of file FSM.cs.
        {
            get => m_Logging;
            set
            {
                m_Logging = value;
                ApplyLoggingToAllStates(m_Logging);
            }
        }
MaxStateChangesPerEvaluate
Int32 MaxStateChangesPerEvaluate = 100 [get], [set]
How many state changes may occur in a single Evaluate() before execution is interrupted.
The value is intended to prevent infinite loops.
Definition at line 77 of file FSM.cs.
{ get; set; } = 100;
Referenced by FSM.Update().
Name
String Name [get]
Name of the Statemachine.
Definition at line 48 of file FSM.cs.
{ get; }
States
State [] States [get]
Definition at line 42 of file FSM.cs.
StaticVars
Variables StaticVars [get]
Global variables are available for all statemachines (be mindful!).
Definition at line 66 of file FSM.cs.
Vars
Variables Vars = new() [get]
These variables are unique to the Statemachine instance.
Definition at line 71 of file FSM.cs.
{ get; } = new();
Event Documentation
OnStateChange
Action<StateChangeEventArgs> OnStateChange
Invoked after each state change.
Definition at line 18 of file FSM.cs.
OnStopped
Action<StatemachineStoppedEventArgs> OnStopped
Invoked when the statemachine entered a final state (state without any transitions).
Definition at line 23 of file FSM.cs.