CmdArgs Class Reference
Parses command line arguments.
Static Public Member Functions
static Boolean Exists (String key)
Does an argument with the given key exist?
static Boolean GetBool (String key, Boolean defaultValue=default)
Gets the argument's value. If the argument was not specified, returns the default value.
static Single GetFloat (String key, Single defaultValue=default)
Gets the argument's value. If the argument was not specified, returns the default value.
static Int32 GetInt (String key, Int32 defaultValue=default)
Gets the argument's value. If the argument was not specified, returns the default value.
static String GetString (String key, String defaultValue=null)
Gets the argument's value. If the argument was not specified, returns the default value.
static void Log ()
Debug.Logs the current command line.
Detailed Description
Parses command line arguments.
Definition at line 16 of file CmdArgs.cs.
Member Function Documentation
Exists()
static Boolean Exists (String key) [static]
Does an argument with the given key exist?
Parameters
key
Returns
GetBool()
static Boolean GetBool (String key, Boolean defaultValue = default) [static]
Gets the argument's value. If the argument was not specified, returns the default value.
Parameters
key
defaultValue
Returns
Referenced by RelayConfig.FromCmdArgs(), and TransportConfig.FromNetworkManagerWithCmdArgOverrides().
GetFloat()
static Single GetFloat (String key, Single defaultValue = default) [static]
Gets the argument's value. If the argument was not specified, returns the default value.
Parameters
key
defaultValue
Returns
GetInt()
static Int32 GetInt (String key, Int32 defaultValue = default) [static]
Gets the argument's value. If the argument was not specified, returns the default value.
Parameters
key
defaultValue
Returns
Referenced by NetcodeConfig.FromCmdArgs(), RelayConfig.FromCmdArgs(), and TransportConfig.FromNetworkManagerWithCmdArgOverrides().
GetString()
static String GetString (String key, String defaultValue = null) [static]
Gets the argument's value. If the argument was not specified, returns the default value.
Parameters
key
defaultValue
Returns
Referenced by RelayConfig.FromCmdArgs(), and TransportConfig.FromNetworkManagerWithCmdArgOverrides().
Log()
static void Log () [static]
Debug.Logs the current command line.
Definition at line 28 of file CmdArgs.cs.
        {
            var sb = new StringBuilder("CmdArgs: ");
            var cmdArgs = Environment.GetCommandLineArgs();
            foreach (var arg in cmdArgs)
            {
                sb.Append(arg.ToLower());
                sb.Append(" ");
            }
            Debug.Log(sb.ToString());
        }