TransportConfig Struct Reference
DTO that provides Transport configuration options.
Static Public Member Functions
static TransportConfig FromNetworkManager ()
Creates a TransportConfig instance from current NetworkManager Transport settings. Use this to get the Transport values set in the Inspector.
static TransportConfig FromNetworkManagerWithCmdArgOverrides ()
Creates a TransportConfig instance from current NetworkManager Transport settings and then have command line arguments (if specified) override each setting.
Public Attributes
String Address
The IP address (v4 or v6) to connect to.
UInt16 Port
The port number for the connection.
String ServerListenAddress
The ServerListenAddress. Should be 0.0.0.0 for publicly accessible games. Use 127.0.0.1 to allow only instances running on the same machine to join. (Default)
Boolean UseEncryption
Enables transport-level encryption.
Boolean UseWebSockets
Enables WebSocket support. Must be enabled for web Clients and the server that web Clients connect to.
Detailed Description
DTO that provides Transport configuration options.
Definition at line 17 of file TransportConfig.cs.
Member Function Documentation
FromNetworkManager()
static TransportConfig FromNetworkManager () [static]
Creates a TransportConfig instance from current NetworkManager Transport settings. Use this to get the Transport values set in the Inspector.
Returns
Definition at line 46 of file TransportConfig.cs.
        {
            var transport = NetworkManager.Singleton.GetTransport();
            var connData = transport.ConnectionData;
            return new TransportConfig
            {
                Address = connData.Address,
                Port = connData.Port,
                ServerListenAddress = connData.ServerListenAddress,
                UseEncryption = transport.UseEncryption,
                UseWebSockets = transport.UseWebSockets,
            };
        }
References TransportConfig.Address, TransportConfig.Port, TransportConfig.ServerListenAddress, TransportConfig.UseEncryption, and TransportConfig.UseWebSockets.
Referenced by TransportConfig.FromNetworkManagerWithCmdArgOverrides().
FromNetworkManagerWithCmdArgOverrides()
static TransportConfig FromNetworkManagerWithCmdArgOverrides () [static]
Creates a TransportConfig instance from current NetworkManager Transport settings and then have command line arguments (if specified) override each setting.
Returns
Definition at line 65 of file TransportConfig.cs.
        {
            var config = FromNetworkManager();
            config.Address = CmdArgs.GetString(nameof(Address), config.Address);
            config.Port = (UInt16)CmdArgs.GetInt(nameof(Port), config.Port);
            config.ServerListenAddress =
                CmdArgs.GetString(nameof(ServerListenAddress), config.ServerListenAddress);
            config.UseEncryption =
                CmdArgs.GetBool(nameof(UseEncryption), config.UseEncryption);
            config.UseWebSockets =
                CmdArgs.GetBool(nameof(UseWebSockets), config.UseWebSockets);
            return config;
        }
References TransportConfig.Address, TransportConfig.FromNetworkManager(), CmdArgs.GetBool(), CmdArgs.GetInt(), CmdArgs.GetString(), TransportConfig.Port, TransportConfig.ServerListenAddress, TransportConfig.UseEncryption, and TransportConfig.UseWebSockets.
Member Data Documentation
Address
String Address
The IP address (v4 or v6) to connect to.
Definition at line 22 of file TransportConfig.cs.
Referenced by TransportConfig.FromNetworkManager(), and TransportConfig.FromNetworkManagerWithCmdArgOverrides().
Port
UInt16 Port
The port number for the connection.
Definition at line 26 of file TransportConfig.cs.
Referenced by TransportConfig.FromNetworkManager(), and TransportConfig.FromNetworkManagerWithCmdArgOverrides().
ServerListenAddress
String ServerListenAddress
The ServerListenAddress. Should be 0.0.0.0 for publicly accessible games. Use 127.0.0.1 to allow only instances running on the same machine to join. (Default)
Definition at line 31 of file TransportConfig.cs.
Referenced by TransportConfig.FromNetworkManager(), and TransportConfig.FromNetworkManagerWithCmdArgOverrides().
UseEncryption
Boolean UseEncryption
Enables transport-level encryption.
Definition at line 35 of file TransportConfig.cs.
Referenced by TransportConfig.FromNetworkManager(), and TransportConfig.FromNetworkManagerWithCmdArgOverrides().
UseWebSockets
Boolean UseWebSockets
Enables WebSocket support. Must be enabled for web Clients and the server that web Clients connect to.
Definition at line 39 of file TransportConfig.cs.
Referenced by TransportConfig.FromNetworkManager(), and TransportConfig.FromNetworkManagerWithCmdArgOverrides().